### ISSUE TITLE
error: cannot bind listener: Address already in use

### ISSUE THREAD

**Issue by xliamren** [ms1995/ella-customized#1]
Following the steps in readme.md
```
./ella.sh s
adb forward tcp:23745 tcp:23745
```

it raises binding error
```
error: cannot bind listener: Address already in use
```

`adb reverse` is exactly closed and when I execute `adb forward` first, the server can not binding too.

**Comment by ms1995** [comment]
@PlyTools I assume you are using Android 4.4. Reverse port forwarding is not supported on Android 4.4, so that's why you saw the error message.

I mentioned that you need a relay app (that accepts two incoming connections and exchange data between them) to get `adb forward` working. I have not released my implementation of this app yet (as I think it should be further improved).

**Comment by ms1995** [comment]
@PlyTools I just released the app. Please see [here](https://github.com/ms1995/tcp-relay-android).

**Comment by xliamren** [comment]
the main problem using Android 4.4 is, I can't using `adb forward tcp:23745 tcp:23745` and `./ella.sh s` at the same time.  Because `adb forward` and `ella` both need listening to port 23745, which is not allowed. 

How did you do it.

**Comment by ms1995** [comment]
@PlyTools I suggest you learn about what `adb forward` does first.

Essentially, you need to run the app on the device, let the Ella agent connect to one port listened by the app, use `adb forward` to forward the other port listened by the app to some port on the computer, and use another TCP relay program (e.g., socat, by running `socat TCP:localhost:23745 TCP:localhost:PORT_BY_ADB_FORWARD`) to finally connect this port to Ella server.
